django_ecommerce/django_ecommerce/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    # goods
    path('', include('goods.urls')),
    # users
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_ecommerce/goods/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from goods.views import HomeView, ProductsListView, ProductsDetailView, VendorsListView, VendorDetailsListView, \
    CategoryListView, CategoryDetailsListView

app_name = 'goods'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/', ProductsListView.as_view(), name='products'),
    path('product/<int:pk>/', ProductsDetailView.as_view()),
    path('vendors/', VendorsListView.as_view(), name='vendors'),
    path('vendor_detail/<int:vendor_id>/', VendorDetailsListView.as_view(), name='vendor_detail'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category_detail/<int:category_id>/', CategoryDetailsListView.as_view(), name='category_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_ecommerce/users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.views import UserCreateView, AuthView, UserLogoutView

app_name = 'users'

urlpatterns = [
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', AuthView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_ecommerce/goods/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Vendor(models.Model):
    name = models.CharField(max_length=15)
    img = models.ImageField(upload_to='vendors', blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True)
    cost = models.IntegerField(null=False)
    img = models.ImageField(upload_to='goods', blank=True, null=True)

    def __str__(self):
        return self.name

django_ecommerce/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class NewUser(AbstractUser):
    email = models.EmailField(unique=True)
    age = models.PositiveIntegerField(default=22)

django_ecommerce/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import NewUser


class NewUserCreationForm(UserCreationForm):
    class Meta:
        model = NewUser
        fields = ('username', 'email', 'password1', 'password2')

django_ecommerce/goods/views.py
from django.views.generic import ListView, DetailView

from .models import Product, Vendor


# Create your views here.
class HomeView(ListView):
    model = Vendor
    template_name = 'home.html'


class ProductsListView(ListView):
    model = Product
    template_name = 'products/products.html'
    # paginate_by = 4


class VendorsListView(ListView):
    model = Product
    template_name = 'products/vendors.html'

    def get_queryset(self):
        object_list = Product.objects.select_related('vendor')
        return object_list.filter(pk__in=[1, 2, 3, 4, 5, 6])
        # return Product.objects.select_related('vendor').distinct()


class CategoryListView(ListView):
    model = Product
    template_name = 'products/categories.html'

    def get_queryset(self):
        object_list = Product.objects.select_related('category')
        return object_list.filter(pk__in=[1, 2, 3, 4])


class ProductsDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'


class VendorDetailsListView(ListView):
    model = Product
    template_name = 'products/vendor_detail.html'

    def get(self, *args, **kwargs):
        self.vendor_id = kwargs['vendor_id']
        return super().get(*args, **kwargs)

    def get_queryset(self):
        return Product.objects.filter(vendor__id=self.vendor_id)


class CategoryDetailsListView(ListView):
    model = Product
    template_name = 'products/category_detail.html'

    def get(self, *args, **kwargs):
        self.category_id = kwargs['category_id']
        return super().get(*args, **kwargs)

    def get_queryset(self):
        return Product.objects.filter(category__id=self.category_id)

django_ecommerce/users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import NewUserCreationForm
from .models import NewUser


class UserCreateView(CreateView):
    model = NewUser
    template_name = 'users/register.html'
    success_url = reverse_lazy('home')
    form_class = NewUserCreationForm


class AuthView(LoginView):
    template_name = 'users/login.html'
    success_url = reverse_lazy('home')


class UserLogoutView(LogoutView):
    pass

django_ecommerce/goods/templates/products/categories.html
{% extends "base.html" %}

{% block content %}
<h1>Categories</h1>
<br>
<ul>
    {% for item in object_list %}
    <li>
        <a href="{% url 'goods:category_detail' category_id=item.category.id %}">{{item.category.name}}</a>
    </li>
    {% endfor %}
</ul>
<br>
<div class="row">
    <div class="col-1">
        <a aria-disabled="true" class="btn btn-warning btn-lg" href="/products/" role="button" tabindex="-1">Back</a>
    </div>
</div>
{% endblock %}

django_ecommerce/goods/templates/products/category_detail.html
{% extends "base.html" %}
{% block title %}

{% endblock %}

{% block content %}
<section class="text-center mb-4">
    <div class="row">
        <div class="col-1">
            <a aria-disabled="true" class="btn btn-warning btn-lg" href="/products/" role="button"
               tabindex="-1">Back</a>
        </div>
    </div>
    <br>
    <div class="row wow fadeIn">
        {% for item in object_list %}
        <div class="col-lg-4 col-md-6 mb-2">
            <div class="card">
                <div class="view overlay">
                    <img height="100px" src="{{item.img.url}}">
                    <div class="mask rgba-white-slight"></div>
                </div>
                <div class="card-body py-2"><a class="product-meta d-block fs-xs"
                                               href="{% url 'goods:category_detail' category_id=item.category.id %}">{{item.category}}</a>
                    <div class="card-body"><a class="product-meta d-block fs-s pb-2"
                                              href="{% url 'goods:vendor_detail' vendor_id=item.vendor.id %}">{{item.vendor}}</a>
                        <h3 class="product-title fs-sm"><a href="/product/{{item.pk}}/">{{item.name}}</a></h3>
                        <div class="d-flex justify-content-between">
                            <div class="product-price"><span class="text-accent">${{item.cost}}.<small>00</small></span>
                            </div>
                            <div class="star-rating"><i class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body card-body-hidden">
                    <div class="text-center pb-2">
                    </div>
                    <button class="btn btn-primary btn-sm d-block w-100 mb-2" type="button"><i
                            class="ci-cart fs-sm me-1"></i>Add to Cart
                    </button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- Pagination-->
    <nav aria-label="Page navigation" class="d-flex justify-content-between pt-2">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#"><i class="ci-arrow-left me-2"></i>Prev</a></li>
        </ul>
        <ul class="pagination">
            <li class="page-item d-sm-none"><span class="page-link page-link-static">1 / 5</span></li>
            <li aria-current="page" class="page-item active d-none d-sm-block"><span class="page-link">1<span
                    class="visually-hidden">(current)</span></span></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">2</a></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">3</a></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">4</a></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">5</a></li>
        </ul>
        <ul class="pagination">
            <li class="page-item"><a aria-label="Next" class="page-link" href="#">Next<i
                    class="ci-arrow-right ms-2"></i></a></li>
        </ul>
    </nav>
</section>
{% endblock %}

django_ecommerce/goods/templates/products/product_detail.html
{% extends "base.html" %}
{% block title %}
{{object.name}}
{% endblock %}

{% block content %}
<div class="bg-light p-5 rounded">
    <h2>{{object.vendor}} {{object.name}}</h2>
    <div class="container">
        <div class="row">
            <div class="col">
                <img src="{{object.img.url}}" width="200px">
            </div>
            <div class="col-8">
                {{object.description}}
                <br>
                <br>
                <div>
                    <button class="btn btn-primary" type="button">
                        <svg class="bi bi-cart-check" fill="currentColor" height="16" viewBox="0 0 16 16"
                             width="16" xmlns="http://www.w3.org/2000/svg">
                            <path d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"></path>
                            <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"></path>
                        </svg>
                        {{object.cost}}$
                    </button>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-8">
                <a aria-disabled="true" class="btn btn-warning btn-lg" href="/products/" role="button" tabindex="-1">Back</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_ecommerce/goods/templates/products/products.html
{% extends "base.html" %}

{% block content %}
<section class="text-center mb-4">
    <div class="row wow fadeIn">
        {% for item in object_list %}
        <div class="col-lg-4 col-md-6 mb-2">
            <div class="card">
                <div class="view overlay">
                    <img height="100px" src="{{item.img.url}}">
                    <div class="mask rgba-white-slight"></div>
                </div>
                <div class="card-body py-2"><a class="product-meta d-block fs-xs"
                                               href="{% url 'goods:category_detail' category_id=item.category.id %}">{{item.category}}</a>
                    <div class="card-body"><a class="product-meta d-block fs-s pb-2"
                                              href="{% url 'goods:vendor_detail' vendor_id=item.vendor.id %}">{{item.vendor}}</a>
                        <h3 class="product-title fs-sm"><a href="/product/{{item.pk}}/">{{item.name}}</a></h3>
                        <div class="d-flex justify-content-between">
                            <div class="product-price"><span class="text-accent">${{item.cost}}.<small>00</small></span>
                            </div>
                            <div class="star-rating"><i class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body card-body-hidden">
                    <div class="text-center pb-2">
                    </div>
                    <button class="btn btn-primary btn-sm d-block w-100 mb-2" type="button">Add to Cart
                    </button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- Pagination-->
    <nav aria-label="Page navigation" class="d-flex justify-content-between pt-2">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#"><i class="ci-arrow-left me-2"></i>Prev</a></li>
        </ul>
        <ul class="pagination">
            <li class="page-item d-sm-none"><span class="page-link page-link-static">1 / 5</span></li>
            <li aria-current="page" class="page-item active d-none d-sm-block"><span class="page-link">1<span
                    class="visually-hidden">(current)</span></span></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">2</a></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">3</a></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">4</a></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">5</a></li>
        </ul>
        <ul class="pagination">
            <li class="page-item"><a aria-label="Next" class="page-link" href="#">Next<i
                    class="ci-arrow-right ms-2"></i></a></li>
        </ul>
    </nav>
</section>
{% endblock %}

django_ecommerce/goods/templates/products/vendor_detail.html
{% extends "base.html" %}
{% block title %}

{% endblock %}

{% block content %}
<section class="text-center mb-4">
    <div class="row">
        <div class="col-1">
            <a aria-disabled="true" class="btn btn-warning btn-lg" href="/products/" role="button"
               tabindex="-1">Back</a>
        </div>
    </div>
    <br>
    <div class="row wow fadeIn">
        {% for item in object_list %}
        <div class="col-lg-4 col-md-6 mb-2">
            <div class="card">
                <div class="view overlay">
                    <img height="100px" src="{{item.img.url}}">
                    <div class="mask rgba-white-slight"></div>
                </div>
                <div class="card-body py-2"><a class="product-meta d-block fs-xs"
                                               href="{% url 'goods:category_detail' category_id=item.category.id %}">{{item.category}}</a>
                    <div class="card-body"><a class="product-meta d-block fs-s pb-2"
                                              href="{% url 'goods:vendor_detail' vendor_id=item.vendor.id %}">{{item.vendor}}</a>
                        <h3 class="product-title fs-sm"><a href="/product/{{item.pk}}/">{{item.name}}</a></h3>
                        <div class="d-flex justify-content-between">
                            <div class="product-price"><span class="text-accent">${{item.cost}}.<small>00</small></span>
                            </div>
                            <div class="star-rating"><i class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star-filled active"></i><i
                                    class="star-rating-icon ci-star"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body card-body-hidden">
                    <div class="text-center pb-2">
                    </div>
                    <button class="btn btn-primary btn-sm d-block w-100 mb-2" type="button"><i
                            class="ci-cart fs-sm me-1"></i>Add to Cart
                    </button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- Pagination-->
    <nav aria-label="Page navigation" class="d-flex justify-content-between pt-2">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#"><i class="ci-arrow-left me-2"></i>Prev</a></li>
        </ul>
        <ul class="pagination">
            <li class="page-item d-sm-none"><span class="page-link page-link-static">1 / 5</span></li>
            <li aria-current="page" class="page-item active d-none d-sm-block"><span class="page-link">1<span
                    class="visually-hidden">(current)</span></span></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">2</a></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">3</a></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">4</a></li>
            <li class="page-item d-none d-sm-block"><a class="page-link" href="#">5</a></li>
        </ul>
        <ul class="pagination">
            <li class="page-item"><a aria-label="Next" class="page-link" href="#">Next<i
                    class="ci-arrow-right ms-2"></i></a></li>
        </ul>
    </nav>
</section>
{% endblock %}

django_ecommerce/goods/templates/products/vendors.html
{% extends "base.html" %}

{% block content %}
<h1>Vendors</h1>
<br>
<ul>
    {% for item in object_list %}
    <li>
        <a href="{% url 'goods:vendor_detail' vendor_id=item.vendor.id %}">{{item.vendor.name}}</a>
    </li>
    {% endfor %}
</ul>
<br>
<div class="row">
    <div class="col-1">
        <a aria-disabled="true" class="btn btn-warning btn-lg" href="/products/" role="button" tabindex="-1">Back</a>
    </div>
</div>
{% endblock %}

django_ecommerce/templates/base.html
{% load static %}

<html lang="en">
<head>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body class="d-flex flex-column h-100">
{% include "navmenu.html" %}
<main class="flex-shrink-0">
    <div class="container">
        <br>
        {% block content %}
        {% endblock %}
    </div>
</main>
<footer class="footer mt-auto py-3">
    <div class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2021 MayIT, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </div>
</footer>
<script src="{% static 'css/bootstrap.min.js' %}"></script>
</body>
</html>

django_ecommerce/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1 align="center">Products from the best brands!</h1>
<br>
<br>
<br>
<section>
    <div class="row">
        {% for item in object_list %}
        <div class="col">
            <div class="view overlay">
                <img height="80px" src="{{ item.img.url }}">
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

django_ecommerce/templates/navmenu.html
<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a class="d-flex align-items-center text-dark text-decoration-none" href="/">
            <span class="fs-4">IT Marketplace</span>
        </a>
        <a class="nav-link active me-md-auto" href="{% url 'users:login' %}">
            <svg class="bi bi-door-open" fill="currentColor" height="26" viewBox="0 0 16 16" width="26"
                 xmlns="http://www.w3.org/2000/svg">
                <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z"/>
                <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117zM11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5zM4 1.934V15h6V1.077l-6 .857z"/>
            </svg>
        </a>
        <ul class="nav nav-pills">
            <li class="nav-item"><a aria-current="page" class="nav-link active" href="{% url 'goods:home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'goods:products' %}">Products</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'goods:vendors' %}">Vendors</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'goods:categories' %}">Categories</a></li>
        </ul>
    </header>
</div>

django_ecommerce/users/templates/users/login.html
{% extends "base.html" %}
{% block title %}
Login
{% endblock %}

{% block content %}
<div class="bg-light p-5 rounded">
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <hr>
        <button class="btn btn-primary" type="submit">Login</button>
        <a class="btn btn-warning" href="{% url 'users:register' %}" role="button">Register</a>
    </form>
</div>
{% endblock %}

django_ecommerce/users/templates/users/register.html
{% extends "base.html" %}
{% block title %}
Registration
{% endblock %}

{% block content %}
<div class="bg-light p-5 rounded">
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <hr>
        <button class="btn btn-primary" type="submit">Register</button>
        <a class="btn btn-warning" href="{% url 'users:login' %}" role="button">Login</a>
    </form>
</div>
{% endblock %}